version: "3.1"
networks:
  frontend:
    external: true
    
services:
  omada-controller:
    container_name: omada
    image: mbentley/omada-controller:latest
    networks:
      - frontend
    ports:
      - '8083:8083'
      - '8843:8843'
      - '8043:8043'

      - '27001:27001/udp'
      - '29810:29810/udp'
      - '29811:29811'
      - '29812:29812'
      - '29813:29813'
      - '29814:29814'
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 60s
    environment:
      - PUID=508
      - PGID=508
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8083
      - PORTAL_HTTPS_PORT=8843
      - PORT_APP_DISCOVERY=27001
      - PORT_ADOPT_V1=29812
      - PORT_UPGRADE_V1=29813
      - PORT_MANAGER_V1=29811
      - PORT_MANAGER_V2=29814
      - PORT_DISCOVERY=29810
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
      - SSL_CERT_NAME=tls.crt
      - SSL_KEY_NAME=tls.key
      - TZ=Etc/UTC
    volumes:
      - omada-data:/opt/tplink/EAPController/data
      - omada-logs:/opt/tplink/EAPController/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.omada.rule=Host(`omada.local.barrett.network`)"
      - "traefik.http.routers.omada.entrypoints=websecure"
      - "traefik.http.routers.omada.tls.certresolver=production"
      - "traefik.http.routers.omada.tls.domains[0].main=*.local.barrett.network"
      - "traefik.http.services.omada.loadbalancer.server.port=8043"
      - "traefik.http.routers.omada.service=omada"
      - "traefik.http.services.omada.loadbalancer.server.scheme=https"
      - "traefik.http.routers.omada.middlewares=omada-middlewares"
      - "traefik.http.middlewares.omada-middlewares.chain.middlewares=omada-redirect@docker,omada-headers@docker"
      - "traefik.http.middlewares.omada-headers.headers.customrequestheaders.Host=omada.local.barrett.network:8043"
      - "traefik.http.middlewares.omada-headers.headers.customresponseheaders.Host=omada.local.barrett.network"
      - "traefik.http.middlewares.omada-redirect.redirectregex.regex=^https:\\/\\/([^\\/]+)\\/?$$"
      - "traefik.http.middlewares.omada-redirect.redirectregex.replacement=https://$$1/omada.local.barrett.network/login"
      - "traefik.http.routers.captiveportal.rule=Host(`captiveportal.local.barrett.network`)"
      - "traefik.http.routers.captiveportal.entrypoints=websecure"
      - "traefik.http.services.captiveportal.loadbalancer.server.port=8843"
      - "traefik.http.routers.captiveportal.service=captiveportal"
      - "traefik.http.services.captiveportal.loadbalancer.server.scheme=https"

volumes:
  omada-data:
  omada-logs: