version: '3.3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "3333:443"
    volumes:
      - /cloudflare-beacon/nginx.conf:/etc/nginx/nginx.conf:ro
      - /cloudflare-beacon/:/certs:ro
    restart: unless-stopped